Srs Traceability
OKKM-insights/OKKM.insights pull request #209
Opened 2024-11-08 01:21 UTC by matpetro

Added in text references and traceability matrixes for requirements / constraints / PUC.
Also removed unneeded SRS folders
Tables:
![image](https://github.com/user-attachments/assets/2c0ee2c9-78f3-427a-a260-2794e231016a)

2024-11-15 03:19 UTC, KyleJMcMaster reviewed
Overall looks great. Just to clarify, there is a rubric requirement to ensure bi-directional navigation in the document (is A refs B, then they both have links to eachother). Is this addressed in another issue? If not, we should make a separate issue and approve this one

2024-11-15 03:20 UTC, KyleJMcMaster requested changes
Matrices should be on separate pages so they arent cut off (`\newpage`)

2024-11-15 19:10 UTC, matpetro commented
I added in a specific related section for the requirements that relate for bidirectional referencing

2024-11-18 00:00 UTC, KyleJMcMaster approved these changes

2024-11-18 00:00 UTC, merged